### ISSUE TITLE
mac_gnrc: No Serial Output

### ISSUE THREAD

**Issue by msolters** [daniel-k/RIOT#3]
Hi, I've been attempting to test a96b58b on the samr21-xpro.  For some reason, when I compile against your `mac_gnrc` branch, I stop getting any serial output over EDBG USB -- this makes it quite difficult to verify that anything is or isn't working, since I can't get any output from the boards.

This isn't localized to the actual duty cycle test application which is of interest, but affects even the `/examples/hello-world`.

By comparison, your `master` branch compiles and works fine (i.e. I can get Hello World working there).

There's many changes in `mac_gnrc` branch of course -- do you have any pointers as to where I might look to get some verifiable output from the board?

Some notes:
-  I am using OpenOCD as built from your repo (0.10.0-dev-g2470d20)
-  The xpro STATUS LED flashes when I send commands -- so I think they are receiving serial communication.  But they never send anything back.

**Comment by daniel-k** [comment]
Totally forgot about this, my fault! I switched baudrate to 921600, so start it like this: `BAUD=921600 make term`. Will update the description. Already thanks for testing :)

**Comment by msolters** [comment]
Yes, that does it!  Thanks for the swift reply.

Working now.  Will continue to poke around.

**Comment by msolters** [comment]
Could you tell me where that baud value is encoded?  I am just trying to understand the structure of this build and where that 921600 comes into play.  I can only locate 3 files containing that integer as an ASCII value, so I figure it must be specified elsewhere.

**Comment by daniel-k** [comment]
That's done in `boards/samr21-xpro/include/board.h`, see [here](https://github.com/daniel-k/RIOT/blob/mac_gnrc/boards/samr21-xpro/include/board.h#L74).

**Comment by msolters** [comment]
:+1:  thank you!

This implementation is frankly much more stable than the ContikiMac support that ATMEL provides via their own ASF modules.  The current consumption is ~~about the same too~~competitive -- going up to about 12mA for TX.  Of course, in "idle" RIOT is still higher -- 7mA as opposed to 4-5mA w/ native ATMEL.

Very, very promising.

**Comment by daniel-k** [comment]
Concerning power consumption. This is designed to to be in µA range when in idle. Of course RX/TX consumption is mostly determined by the hardware (okay, you can lower TX power and use some RX power reduction features), but when in idle, i.e. the MAC layer is `SLEEPING`, the transceiver is turned off and LPM of RIOT should put the system to sleep.
At the moment this is not thoroughly tested. I had some problems in the past when I tried putting the system to `OFF` (refer 650d682f, 9b5f56a48). In RIOT, `OFF` translates to lowest possible power mode for `samr21-xpro`, while `POWERDOWN` is the lowest idle mode.

**Comment by daniel-k** [comment]
Just ran a short test changing (`core/kernel_init.c`):

``` c
        if (lpm_prevent_sleep) {
            lpm_set(LPM_IDLE);
        }
        else {
            lpm_set(LPM_IDLE);
        }
```

to

``` c
        if (lpm_prevent_sleep) {
            lpm_set(LPM_IDLE);
        }
        else {
            lpm_set(LPM_OFF); /* <------- */
        }
```

looks like that it works on the receiver side. I don't have my power measurement equipment at home, so I can't verify if it really goes to sleep as expected. But beware that with this setting you will need to take of wakeup sources for your code to work. Especially UART might not work as expected. This is something that's on the roadmap for RIOT now.

I'd be happy to know what you're might be using this for, just out of curiosity :smile:

**Comment by msolters** [comment]
I only have on hand a multimeter so it's hard for me to grab these quick changes, but the above alteration to `core/kernel_init.c` reads as alternating between 1.3-1.8mA.

Yes, I see that simple substitution makes the board effectively unusable as a sender.

**Comment by daniel-k** [comment]
> [...] but the above alteration to `core/kernel_init.c` reads as alternating between 1.3-1.8mA.

Hmm, it should actually be around 20µA. I guess the multimeter isn't able to adapt to the fast changing current (several µA to 25mA), the cycle is set to 100ms at the moment. You could try to increase `LWMAC_WAKEUP_INTERVAL_US` [here](https://github.com/daniel-k/RIOT/blob/a96b58be0600f33cd148e28fe11fee48b42c8f4a/sys/include/net/gnrc/lwmac/lwmac.h#L68) to something like 5 seconds, then you should be able to see powerdown consumption with your multimeter.

**Comment by msolters** [comment]
Excellent information! Will try at next opportunity.

**Comment by msolters** [comment]
I've had an opportunity to test this today.  Leaving aside low power as a separate issue (i.e., assume `lpm_set(LPM_IDLE)` for both IF and ELSE) I am seeing a pretty stable radio reliability.

There is one problem I've noticed, which is that I tend to get duplicate messages sometimes.  Here's an example sender/receiver pair of applications:  https://github.com/msolters/riot-applications

The sender broadcasts an indexed timestamp every 3 seconds.  The receiver has a simple thread that simply prints out each received message's data.

Quite frequently, a message will "arrive" twice.

I wonder if this has anything to do with the duty cycling somehow grabbing a packet twice - I'm not sure if you implement packet strobing as ContikiMac does?

**Comment by msolters** [comment]
Here's an example dump, first 50 messages as reported by the "receiver" app:

```
Msg 1: It is now 6009399
Msg 2: It is now 9009399
Msg 2: It is now 9009399
Msg 3: It is now 12009399
Msg 4: It is now 15009399
Msg 5: It is now 18009399
Msg 6: It is now 21009399
Msg 7: It is now 24009399
Msg 8: It is now 27009406
Msg 9: It is now 30009399
Msg 10: It is now 33009399
Msg 11: It is now 36009399
Msg 12: It is now 39009399
Msg 13: It is now 42009399
Msg 14: It is now 45009406
Msg 15: It is now 48009399
Msg 16: It is now 51009399
Msg 17: It is now 54009399
Msg 18: It is now 57009399
Msg 19: It is now 60009399
Msg 20: It is now 63009406
Msg 21: It is now 66009399
Msg 22: It is now 69009399
Msg 23: It is now 72009399
Msg 24: It is now 75009399
Msg 25: It is now 78009399
Msg 26: It is now 81009399
Msg 26: It is now 81009399
Msg 27: It is now 84009399
Msg 28: It is now 87009399
Msg 29: It is now 90009399
Msg 30: It is now 93009399
Msg 31: It is now 96009399
Msg 32: It is now 99009399
Msg 32: It is now 99009399
Msg 33: It is now 102009406
Msg 34: It is now 105009399
Msg 35: It is now 108009399
Msg 36: It is now 111009399
Msg 37: It is now 114009399
Msg 38: It is now 117009399
Msg 39: It is now 120009406
Msg 40: It is now 123009399
Msg 41: It is now 126009399
Msg 42: It is now 129009399
Msg 43: It is now 132009399
Msg 44: It is now 135009399
Msg 45: It is now 138009399
Msg 45: It is now 138009399
Msg 46: It is now 141009406
Msg 47: It is now 144009399
Msg 48: It is now 147009399
Msg 49: It is now 150009399
Msg 50: It is now 153009399
```

Note that message 2, 32 & 45 both appear twice in this set.

**Comment by daniel-k** [comment]
That's strange because eacf00360 should make sure that exactly this shouldn't happen. Will look into this, thanks for reporting. Could we maybe switch to https://github.com/RIOT-OS/RIOT/pull/3730 so that other people can track this?

**Comment by msolters** [comment]
Oh yeah, right on, this issue has certainly run its course.  I'll repost over there.

**Comment by daniel-k** [comment]
Just for your current problem here: if I understand [this](https://github.com/msolters/riot-applications/blob/69be7ec9b62216cc48f99d07e9748cf2af7bff1a/receiver/process_msgs.c#L25-L26) correctly you output the string on the receiver side of each individual packet. So if `Msg %d: It is ...` keeps increasing, I would say that there are no duplicate packages. Am I right?
